global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "fskhttp_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'fskhttp'
    static_configs:
      - targets: ['fskhttp-1:8080', 'fskhttp-2:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  - job_name: 'fskhttp-health'
    static_configs:
      - targets: ['fskhttp-1:8080', 'fskhttp-2:8080']
    scrape_interval: 30s
    metrics_path: /health
    scheme: http

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

